/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gui;

import com.dao.TaiKhoanDAO;
import com.entity.TaiKhoanEntity;
import com.file.FileExtensison;
import com.utils.MsgBox;
import com.utils.XDate;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author DAVISY
 */
public class CaiDat extends javax.swing.JDialog {

    /**
     * Creates new form TaiKhoanCaNhan
     */
    public CaiDat(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        FileExtensison fe = new FileExtensison();
        try {
            txtQrProduct.setText(fe.getPath());
            txtBanerPathImg1.setText(fe.getImgBaner1());
            txtBanerPathImg2.setText(fe.getImgBaner2());
            txtBanerPathImg3.setText(fe.getImgBaner3());
        } catch (Exception ex) {
            Logger.getLogger(CaiDat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void chooserFile() throws FileNotFoundException, Exception {
        FileExtensison fe = new FileExtensison();

        //Lấy đường dẫn lưu mã QR
        JButton open = new JButton();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File(""));
        fileChooser.setDialogTitle("Chọn đường dẫn lưu mã đăng nhập!");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (fileChooser.showOpenDialog(open) == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            //System.out.println(fileChooser.getSelectedFile().getAbsolutePath());
            txtQrProduct.setText(path);
            fe.setPath(path);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cardTaiKhoanCaNhan = new com.swing.PanelRound();
        jLabel60 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtQrProduct = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtBanerPathImg1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtBanerPathImg2 = new javax.swing.JTextField();
        txtBanerPathImg3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        button1 = new com.swing.Button();
        button2 = new com.swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cardTaiKhoanCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        cardTaiKhoanCaNhan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/manager.png"))); // NOI18N
        cardTaiKhoanCaNhan.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel14.setText("Cài đặt");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardTaiKhoanCaNhan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 280, 40));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("Thư mục lưu đường dẫn mã QR sản phẩm: ");
        cardTaiKhoanCaNhan.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 590, 29));

        txtQrProduct.setEditable(false);
        txtQrProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQrProduct.setText("src\\\\com\\\\product");
        cardTaiKhoanCaNhan.add(txtQrProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 593, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/open.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        cardTaiKhoanCaNhan.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, 41, 46));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 204));
        jLabel19.setText("Đường dẫn banner ảnh trang chính:");
        cardTaiKhoanCaNhan.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 590, 29));

        txtBanerPathImg1.setEditable(false);
        txtBanerPathImg1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cardTaiKhoanCaNhan.add(txtBanerPathImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 589, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/open.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        cardTaiKhoanCaNhan.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, 41, 38));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/open.png"))); // NOI18N
        cardTaiKhoanCaNhan.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 370, 41, 38));

        txtBanerPathImg2.setEditable(false);
        txtBanerPathImg2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cardTaiKhoanCaNhan.add(txtBanerPathImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 589, 29));

        txtBanerPathImg3.setEditable(false);
        txtBanerPathImg3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cardTaiKhoanCaNhan.add(txtBanerPathImg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 589, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/open.png"))); // NOI18N
        cardTaiKhoanCaNhan.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, 41, 50));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("1:");
        cardTaiKhoanCaNhan.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 32, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("2:");
        cardTaiKhoanCaNhan.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 32, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("3:");
        cardTaiKhoanCaNhan.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 32, 30));

        button1.setBackground(new java.awt.Color(204, 204, 255));
        button1.setLabel("Khôi phục");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        cardTaiKhoanCaNhan.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 500, 100, -1));

        button2.setBackground(new java.awt.Color(204, 204, 255));
        button2.setLabel("Khôi phục");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        cardTaiKhoanCaNhan.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 190, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cardTaiKhoanCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cardTaiKhoanCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        try {
            chooserFile();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CaiDat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CaiDat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        FileExtensison fe = new FileExtensison();
        try {
            fe.setPath("src\\com\\images\\product");
            txtQrProduct.setText("src\\com\\images\\product");
        } catch (Exception ex) {
            MsgBox.alert(this, "Thao tác không thành công!");
            //Logger.getLogger(CaiDat.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       FileExtensison fe = new FileExtensison();
        try {
            fe.setImgBaner1("src\\com\\asset\\slide-login\\bn1.jpeg");
            txtBanerPathImg1.setText("src\\com\\asset\\slide-login\\bn1.jpeg");
            fe.setImgBaner2("src\\com\\asset\\slide-login\\bn2.jpg" );
            txtBanerPathImg2.setText("src\\com\\asset\\slide-login\\bn2.jpg");
            fe.setImgBaner3("src\\com\\asset\\slide-login\\bn3.jpg");
            txtBanerPathImg3.setText("src\\com\\asset\\slide-login\\bn3.jpg");
        } catch (Exception ex) {
            MsgBox.alert(this, "Thao tác không thành công!");
            //Logger.getLogger(CaiDat.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_button1ActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CaiDat dialog = new CaiDat(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.swing.Button button1;
    private com.swing.Button button2;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.swing.PanelRound cardTaiKhoanCaNhan;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JTextField txtBanerPathImg1;
    private javax.swing.JTextField txtBanerPathImg2;
    private javax.swing.JTextField txtBanerPathImg3;
    private javax.swing.JTextField txtQrProduct;
    // End of variables declaration//GEN-END:variables
}
