/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gui;

import com.dao.TaiKhoanDAO;
import com.entity.TaiKhoanEntity;
import com.utils.MsgBox;
import com.utils.XDate;
import javax.swing.JFrame;

/**
 *
 * @author DAVISY
 */
public class MyAccount extends javax.swing.JDialog {
    
    TaiKhoanDAO NhanVien = new TaiKhoanDAO();
    String ktTenDNTK = null;

    /**
     * Creates new form TaiKhoanCaNhan
     */
    public MyAccount(java.awt.Frame parent, boolean modal, String ktTenDN) {
        super(parent, modal);
        initComponents();
        txtMatKhauTK.setEchoChar('●');
        txtNhapLaiMatKhauTK.setEchoChar('●');
        lblHide.setVisible(false);
        lblHide1.setVisible(false);
        ktTenDNTK = ktTenDN;
        setFormThongTinNhanVien();
    }
    
    private MyAccount(JFrame jFrame, boolean modal) {
        initComponents();
        setResizable(false);
        txtMatKhauTK.setEchoChar('●');
        txtNhapLaiMatKhauTK.setEchoChar('●');
        lblHide.setVisible(false);
        lblHide1.setVisible(false);
        ktTenDNTK = "dannk";
        setFormThongTinNhanVien();
    }
    
    public void setFormThongTinNhanVien() {
        TaiKhoanEntity tk = NhanVien.selectById(ktTenDNTK);
        txtHoTenTK.setText(tk.getTenNV());
        txtTenDNTK.setText(tk.getTenDN());
        txtMatKhauTK.setText(tk.getMatKhau());
        txtEmailTK.setText(tk.getEmail());
        txtSDTNVTK.setText(tk.getDienThoai());
        txtDiaChiTK.setText(tk.getDiaChi());
        txtNgaySinhTK.setText(String.valueOf(tk.getNgaySinh()));
        rdoNamTK.setSelected(tk.isGioiTInh());
        rdoNuTK.setSelected(!tk.isGioiTInh());
    }
    
    public void updateThongTinCaNhan() {
        if (txtMatKhauTK.getText().equalsIgnoreCase(txtNhapLaiMatKhauTK.getText())) {
            TaiKhoanEntity nv = getFormThongTinNhanVien();
            try {
                NhanVien.update(nv);
                MsgBox.alert(this, "Cập nhật thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Cập nhật thất bại!");
                System.out.println(e);
            }
            
        } else {
            MsgBox.alert(this, "Mật khẩu không chính xác!");
            txtNhapLaiMatKhauTK.setText("");
            txtNhapLaiMatKhauTK.requestFocus();
            return;
        }
    }
    
    public TaiKhoanEntity getFormThongTinNhanVien() {
        TaiKhoanEntity h = new TaiKhoanEntity();
        h.setTenDN(txtTenDNTK.getText());
        h.setTenNV(txtHoTenTK.getText());
        h.setEmail(txtEmailTK.getText());
        h.setMatKhau(txtMatKhauTK.getText());
        h.setDiaChi(txtDiaChiTK.getText());
        h.setDienThoai(txtSDTNVTK.getText());
        h.setNgaySinh(XDate.toDate(txtNgaySinhTK.getText(), "yyyy-MM-dd"));
        h.setGioiTInh(rdoNamTK.isSelected());
        return h;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cardTaiKhoanCaNhan = new com.swing.PanelRound();
        jLabel60 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtHoTenTK = new javax.swing.JTextField();
        txtTenDNTK = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        txtEmailTK = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        txtNgaySinhTK = new javax.swing.JTextField();
        jLabel115 = new javax.swing.JLabel();
        txtDiaChiTK = new javax.swing.JTextField();
        jLabel116 = new javax.swing.JLabel();
        txtSDTNVTK = new javax.swing.JTextField();
        jLabel122 = new javax.swing.JLabel();
        rdoNamTK = new javax.swing.JRadioButton();
        rdoNuTK = new javax.swing.JRadioButton();
        btnCapNhatTK = new com.swing.Button();
        jLabel53 = new javax.swing.JLabel();
        lblHide = new javax.swing.JLabel();
        lblShow = new javax.swing.JLabel();
        lblHide1 = new javax.swing.JLabel();
        lblShow1 = new javax.swing.JLabel();
        txtNhapLaiMatKhauTK = new textfield.PasswordField();
        txtMatKhauTK = new textfield.PasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cardTaiKhoanCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        cardTaiKhoanCaNhan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/businessman.png"))); // NOI18N
        cardTaiKhoanCaNhan.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel14.setText("Tài khoản cá nhân");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardTaiKhoanCaNhan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 54, 280, 40));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel37.setText("Họ và tên:");
        jLabel37.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardTaiKhoanCaNhan.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 110, 30));

        txtHoTenTK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHoTenTK.setForeground(new java.awt.Color(255, 0, 0));
        txtHoTenTK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cardTaiKhoanCaNhan.add(txtHoTenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 180, 30));

        txtTenDNTK.setEditable(false);
        txtTenDNTK.setBackground(new java.awt.Color(255, 255, 255));
        txtTenDNTK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTenDNTK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cardTaiKhoanCaNhan.add(txtTenDNTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 180, 30));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel51.setText("Tên đăng nhập:");
        jLabel51.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardTaiKhoanCaNhan.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 110, 30));

        jLabel52.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel52.setText("Mật khẩu:");
        jLabel52.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardTaiKhoanCaNhan.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 110, 30));

        jLabel66.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 0, 255));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel66.setText("Email:");
        jLabel66.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardTaiKhoanCaNhan.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 110, 30));

        txtEmailTK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmailTK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cardTaiKhoanCaNhan.add(txtEmailTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 180, 30));

        jLabel82.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(0, 0, 255));
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel82.setText("Ngày sinh:");
        jLabel82.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardTaiKhoanCaNhan.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 110, 30));

        txtNgaySinhTK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNgaySinhTK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cardTaiKhoanCaNhan.add(txtNgaySinhTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 180, 30));

        jLabel115.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(0, 0, 255));
        jLabel115.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel115.setText("Địa chỉ:");
        jLabel115.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardTaiKhoanCaNhan.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 110, 30));

        txtDiaChiTK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDiaChiTK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cardTaiKhoanCaNhan.add(txtDiaChiTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 180, 30));

        jLabel116.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(0, 0, 255));
        jLabel116.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel116.setText("Số diện thoại:");
        jLabel116.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardTaiKhoanCaNhan.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 110, 30));

        txtSDTNVTK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSDTNVTK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cardTaiKhoanCaNhan.add(txtSDTNVTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 180, 30));

        jLabel122.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(0, 0, 255));
        jLabel122.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel122.setText("Giới tính:");
        jLabel122.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardTaiKhoanCaNhan.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 110, 30));

        rdoNamTK.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoNamTK);
        rdoNamTK.setText("Nam");
        cardTaiKhoanCaNhan.add(rdoNamTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 50, -1));

        rdoNuTK.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoNuTK);
        rdoNuTK.setText("Nữ");
        cardTaiKhoanCaNhan.add(rdoNuTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 40, -1));

        btnCapNhatTK.setBackground(new java.awt.Color(204, 204, 255));
        btnCapNhatTK.setText("Cập nhật");
        btnCapNhatTK.setEffectColor(new java.awt.Color(204, 255, 204));
        btnCapNhatTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatTKActionPerformed(evt);
            }
        });
        cardTaiKhoanCaNhan.add(btnCapNhatTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 116, 39));

        jLabel53.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 255));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel53.setText("Nhập lại mật khẩu:");
        jLabel53.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardTaiKhoanCaNhan.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 130, 30));

        lblHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/hide.png"))); // NOI18N
        lblHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHideMouseClicked(evt);
            }
        });
        cardTaiKhoanCaNhan.add(lblHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        lblShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/show.png"))); // NOI18N
        lblShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowMouseClicked(evt);
            }
        });
        cardTaiKhoanCaNhan.add(lblShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        lblHide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/hide.png"))); // NOI18N
        lblHide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHide1MouseClicked(evt);
            }
        });
        cardTaiKhoanCaNhan.add(lblHide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        lblShow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/show.png"))); // NOI18N
        lblShow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShow1MouseClicked(evt);
            }
        });
        cardTaiKhoanCaNhan.add(lblShow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        txtNhapLaiMatKhauTK.setLabelText("");
        cardTaiKhoanCaNhan.add(txtNhapLaiMatKhauTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 180, -1));

        txtMatKhauTK.setLabelText("");
        cardTaiKhoanCaNhan.add(txtMatKhauTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cardTaiKhoanCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cardTaiKhoanCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatTKActionPerformed
        updateThongTinCaNhan();
    }//GEN-LAST:event_btnCapNhatTKActionPerformed

    private void lblShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowMouseClicked
        lblShow.setVisible(false);
        lblHide.setVisible(true);
        txtMatKhauTK.setEchoChar((char) 0);
    }//GEN-LAST:event_lblShowMouseClicked

    private void lblHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHideMouseClicked
        lblHide.setVisible(false);
        lblShow.setVisible(true);
        txtMatKhauTK.setEchoChar('●');
    }//GEN-LAST:event_lblHideMouseClicked

    private void lblHide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHide1MouseClicked
        lblHide1.setVisible(false);
        lblShow1.setVisible(true);
        txtNhapLaiMatKhauTK.setEchoChar('●');
    }//GEN-LAST:event_lblHide1MouseClicked

    private void lblShow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShow1MouseClicked
        lblShow1.setVisible(false);
        lblHide1.setVisible(true);
        txtNhapLaiMatKhauTK.setEchoChar((char) 0);
    }//GEN-LAST:event_lblShow1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MyAccount dialog = new MyAccount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.swing.Button btnCapNhatTK;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.swing.PanelRound cardTaiKhoanCaNhan;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel lblHide;
    private javax.swing.JLabel lblHide1;
    private javax.swing.JLabel lblShow;
    private javax.swing.JLabel lblShow1;
    private javax.swing.JRadioButton rdoNamTK;
    private javax.swing.JRadioButton rdoNuTK;
    private javax.swing.JTextField txtDiaChiTK;
    private javax.swing.JTextField txtEmailTK;
    private javax.swing.JTextField txtHoTenTK;
    private textfield.PasswordField txtMatKhauTK;
    private javax.swing.JTextField txtNgaySinhTK;
    private textfield.PasswordField txtNhapLaiMatKhauTK;
    private javax.swing.JTextField txtSDTNVTK;
    private javax.swing.JTextField txtTenDNTK;
    // End of variables declaration//GEN-END:variables
}
